services: 

  db-projeto-fullstack:
    container_name: db_projeto_fullstack
    build:
      context: ./backend
      dockerfile: Dockerfile-pgsql
    restart: always
    ports:
      - "5433:5432"
    networks:
      - projeto-fullstack
    volumes:
      - "db-projeto-fullstack:/var/lib/postgresql/data"
  
  redis-projeto-fullstack:
    container_name: redis_projeto_fullstack
    build:
      context: ./backend
      dockerfile: Dockerfile-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - projeto-fullstack

  app-projeto-fullstack:
    container_name: app_projeto_fullstack
    build:
      context: ./backend
      dockerfile: Dockerfile-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db-projeto-fullstack
      - redis-projeto-fullstack
    networks:
      - projeto-fullstack

  frontend-projeto-fullstack:
    container_name: frontend_projeto_fullstack
    build:
      context: ./frontend
      dockerfile: Dockerfile-angular
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - projeto-fullstack
    depends_on:
      - db-projeto-fullstack
      - redis-projeto-fullstack
      - app-projeto-fullstack

volumes:
  db-projeto-fullstack:
    driver: local

networks:
  projeto-fullstack:
    driver: bridge