[default]
    ALLOWED_ORIGINS = [
        "http://127.0.0.1:4200", 
        "http://localhost:4200",
        "http://127.0.0.1:8000", 
        "http://localhost:8000"
    ]
    ALLOWED_METHODS = [
        "GET", 
        "POST", 
        "PUT", 
        "DELETE", 
        "OPTIONS"
    ]
    ALLOWED_HEADERS = [
        "Content-Type", 
        "Authorization"
    ]
    ALLOWED_CREDENTIALS = true
    DEBUG = false
    SECRET_KEY = "Techsolutio@2025##"
    ALGORITHM = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES = 15
    REFRESH_TOKEN_EXPIRE_DAYS = 1

[testing]
    APP_NAME = "testing"
    DATABASE_URL = "postgresql://techsolutio:techsolutio@127.0.0.1:5433/techsolutio"
    REDIS_HOST = "localhost"
    REDIS_PORT = "6380"

[homologation]
    APP_NAME = "homologation"
    DATABASE_URL = "postgresql://techsolutio:techsolutio@db-projeto-fullstack:5432/techsolutio"
    REDIS_HOST = "redis-projeto-fullstack"
    REDIS_PORT = "6379"

[production]
    APP_NAME = "production"
    DATABASE_URL = "postgresql://techsolutio:techsolutio@db-projeto-fullstack:5432/techsolutio"
    REDIS_HOST = "redis-projeto-fullstack"
    REDIS_PORT = "6379"

